<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DagNumberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DagNumberRepository extends EntityRepository
{

    public function getDagNumbersByMouza($mouza){
        $qb = $this->createQueryBuilder('d');
        $qb->where('d.mouza = :mouza');
        $qb->setParameter('mouza',$mouza);

        return $qb->getQuery()->getResult();
    }

    public function getDagNumbersByMouzaWithPlr($mouza){
//        var_dump($mouza);die;
        $qb = $this->createQueryBuilder('d');
        $qb->Join('d.purchasedLandRelations', 'plr');
        $qb ->distinct('d.id');
        $qb->where('d.mouza = :mouza');
        $qb->setParameter('mouza',$mouza);

        return $qb->getQuery()->getResult();
    }

}
