<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DagNumberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DagNumberRepository extends EntityRepository
{


}
