<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends EntityRepository
{
    public function delete($data)
    {
        $this->_em->remove($data);
        $this->_em->flush();
    }
}
