<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * PlotRecordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlotRecordRepository extends EntityRepository
{
    public function create($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
    }

    public function getPlotRecordList(){

        $qb = $this->_em->getRepository('AppBundle:PlotRecord')->createQueryBuilder('pr');
        $qb->select('pr');
        $qb->addSelect('SUM(prr.dagArea) AS totalArea');
        $qb->join('pr.plotRecordRelation', 'prr');
        $qb->groupBy('prr.plotRecord');
        $qb->orderBy('pr.id','ASC');
        return $qb->getQuery()->getArrayResult();

    }

}
