<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * PlotRecordRelationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlotRecordRelationRepository extends EntityRepository
{

}
