<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * PurchasedLandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PurchasedLandRepository extends EntityRepository
{
    public function create($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
    }

    public function getPurchasedLandList(){

        $qb = $this->_em->getRepository('AppBundle:PurchasedLand')->createQueryBuilder('pl');
        $qb->select('pl');
        $qb->addSelect('SUM(plr.purchasedTotalArea) AS totalArea');
        $qb->join('pl.purchasedLandRelation', 'plr');
        $qb->groupBy('plr.purchasedLand');
        $qb->orderBy('pl.id','ASC');
        return $qb->getQuery()->getArrayResult();

    }

}
