<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * PurchasedLandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PurchasedLandRepository extends EntityRepository
{
    public function create($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
    }
}
