<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * PurchasedLandRelationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PurchasedLandRelationRepository extends EntityRepository
{
    public function create($data)
    {
        var_dump($data);die;
        $this->_em->persist($data);
        $this->_em->flush();
    }
}
