app:
    resource: "@AppBundle/Controller/"
    type:     annotation

rbs_user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

app_bundle:
    resource: "@AppBundle/Resources/config/routing.yml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

user_bundle:
    resource: "@UserBundle/Resources/config/routing.yml"
