dashboard:
    path:     /dashboard
    defaults: { _controller: AppBundle:Dashboard:index }

purchased_land_list:
    path:     /purchased-land-list
    defaults: { _controller: AppBundle:PurchasedLand:index }

purchased_land_add:
    path:     /purchased-land-add
    defaults: { _controller: AppBundle:PurchasedLand:createPurchasedLand }

purchased_land_update:
    path:     /purchased-land-edit/{id}
    defaults: { _controller: AppBundle:PurchasedLand:updatePurchasedLand }

mouza_add:
    path:     /mouza/add
    defaults: { _controller: AppBundle:Mouza:createMouza }
    options:
            expose: true

mouzas_list:
    path:     /mouza/list
    defaults: { _controller: AppBundle:Mouza:index }
    options:
            expose: true

get_dagnumber_by_mouza:
    path:     /mouza/{id}/{dagId}
    defaults:
            _controller: AppBundle:DagNumber:getDagNumber
            mouzaId: 0
            dagId: 0
    methods: [GET]
    options:
           expose: true

get_dagnumber_mouza_id:
    path:     /plot-mouza/{id}
    defaults: { _controller: AppBundle:DagNumber:getDagNumberByMouzaId}
    methods: [GET]
    options:
           expose: true

dag_number_add:
    path:     /dagnumber/{mouzaId}/add
    defaults:
            _controller: AppBundle:DagNumber:createDagNumber
            mouzaId: 0
    methods: [GET,POST]
    options:
            expose: true

document_delete:
    path:     /document_delete/{id}
    defaults: { _controller: AppBundle:PurchasedLand:documentDelete }
    options:
            expose: true

plot_record_add:
    path:     /plot-record-add
    defaults: { _controller: AppBundle:PlotRecord:createPlotRecord }
